config/routes.rb
Rails.application.routes.draw do
  resources :productos
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :precio, :estado, :categoria)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Inventariado App', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Nosotros', home_about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Lista de Productos', productos_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Acerca de nosotros</h1>

app/views/home/index.html.erb
<h1>Hola Mundo!</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Inventario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      
      <div class="my-3">
        <%= yield %>
      </div>
    </div>
    
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.number_field :precio %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.number_field :estado %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_field :categoria %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p>
    <strong>Nombre:</strong>
    <%= producto.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= producto.descripcion %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= producto.precio %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= producto.estado %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= producto.categoria %>
  </p>

</div>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Show this producto", @producto %> |
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Productos</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
      <th scope="col">Estado</th>
      <th scope="col">Categoria</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr id="<%= dom_id producto %>">
      <th scope="row"><%= producto.nombre %></th>
      <td><%= producto.descripcion %></td>
      <td><%= producto.precio %> </td>
      <td><%= producto.estado %></td>
      <th><%= producto.categoria %></th>
      <td><%= link_to "Detalle", producto, class: "btn btn-sm btn-primary" %></td>
      <td><%= link_to "Editar", edit_producto_path(producto), class: "btn btn-sm btn-primary" %> </td>
      <td><%= button_to "Eliminar", producto, method: :delete, class: "btn btn-sm btn-danger" %></td>
    </tr>
    <% end %>
    
  </tbody>
</table>

<%= link_to "New producto", new_producto_path, class: "btn btn-lg btn-secondary"%> 

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= link_to "Edit this producto", edit_producto_path(@producto) %> |
  <%= link_to "Back to productos", productos_path %>

  <%= button_to "Destroy this producto", @producto, method: :delete %>
</div>